package com.hhwy.pm.qqch.review.mapper.ext;

import com.hhwy.pm.qqch.review.domain.Review;
import com.hhwy.pm.qqch.review.domain.ReviewExtExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ReviewExtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    int countByExample(ReviewExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    int deleteByExample(ReviewExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    int insert(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    int insertSelective(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    List<Review> selectByExampleWithBLOBs(ReviewExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    List<Review> selectByExample(ReviewExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    Review selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    int updateByExampleSelective(@Param("record") Review record, @Param("example") ReviewExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") Review record, @Param("example") ReviewExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    int updateByExample(@Param("record") Review record, @Param("example") ReviewExtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    int updateByPrimaryKeySelective(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    int updateByPrimaryKey(Review record);
}