package com.hhwy.pm.qqch.review.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ReviewExtExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    public ReviewExtExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andReviewNameIsNull() {
            addCriterion("review_name is null");
            return (Criteria) this;
        }

        public Criteria andReviewNameIsNotNull() {
            addCriterion("review_name is not null");
            return (Criteria) this;
        }

        public Criteria andReviewNameEqualTo(String value) {
            addCriterion("review_name =", value, "reviewName");
            return (Criteria) this;
        }

        public Criteria andReviewNameNotEqualTo(String value) {
            addCriterion("review_name <>", value, "reviewName");
            return (Criteria) this;
        }

        public Criteria andReviewNameGreaterThan(String value) {
            addCriterion("review_name >", value, "reviewName");
            return (Criteria) this;
        }

        public Criteria andReviewNameGreaterThanOrEqualTo(String value) {
            addCriterion("review_name >=", value, "reviewName");
            return (Criteria) this;
        }

        public Criteria andReviewNameLessThan(String value) {
            addCriterion("review_name <", value, "reviewName");
            return (Criteria) this;
        }

        public Criteria andReviewNameLessThanOrEqualTo(String value) {
            addCriterion("review_name <=", value, "reviewName");
            return (Criteria) this;
        }

        public Criteria andReviewNameLike(String value) {
            addCriterion("review_name like", value, "reviewName");
            return (Criteria) this;
        }

        public Criteria andReviewNameNotLike(String value) {
            addCriterion("review_name not like", value, "reviewName");
            return (Criteria) this;
        }

        public Criteria andReviewNameIn(List<String> values) {
            addCriterion("review_name in", values, "reviewName");
            return (Criteria) this;
        }

        public Criteria andReviewNameNotIn(List<String> values) {
            addCriterion("review_name not in", values, "reviewName");
            return (Criteria) this;
        }

        public Criteria andReviewNameBetween(String value1, String value2) {
            addCriterion("review_name between", value1, value2, "reviewName");
            return (Criteria) this;
        }

        public Criteria andReviewNameNotBetween(String value1, String value2) {
            addCriterion("review_name not between", value1, value2, "reviewName");
            return (Criteria) this;
        }

        public Criteria andStageIsNull() {
            addCriterion("stage is null");
            return (Criteria) this;
        }

        public Criteria andStageIsNotNull() {
            addCriterion("stage is not null");
            return (Criteria) this;
        }

        public Criteria andStageEqualTo(String value) {
            addCriterion("stage =", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageNotEqualTo(String value) {
            addCriterion("stage <>", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageGreaterThan(String value) {
            addCriterion("stage >", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageGreaterThanOrEqualTo(String value) {
            addCriterion("stage >=", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageLessThan(String value) {
            addCriterion("stage <", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageLessThanOrEqualTo(String value) {
            addCriterion("stage <=", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageLike(String value) {
            addCriterion("stage like", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageNotLike(String value) {
            addCriterion("stage not like", value, "stage");
            return (Criteria) this;
        }

        public Criteria andStageIn(List<String> values) {
            addCriterion("stage in", values, "stage");
            return (Criteria) this;
        }

        public Criteria andStageNotIn(List<String> values) {
            addCriterion("stage not in", values, "stage");
            return (Criteria) this;
        }

        public Criteria andStageBetween(String value1, String value2) {
            addCriterion("stage between", value1, value2, "stage");
            return (Criteria) this;
        }

        public Criteria andStageNotBetween(String value1, String value2) {
            addCriterion("stage not between", value1, value2, "stage");
            return (Criteria) this;
        }

        public Criteria andReviewDeptIdIsNull() {
            addCriterion("review_dept_id is null");
            return (Criteria) this;
        }

        public Criteria andReviewDeptIdIsNotNull() {
            addCriterion("review_dept_id is not null");
            return (Criteria) this;
        }

        public Criteria andReviewDeptIdEqualTo(Long value) {
            addCriterion("review_dept_id =", value, "reviewDeptId");
            return (Criteria) this;
        }

        public Criteria andReviewDeptIdNotEqualTo(Long value) {
            addCriterion("review_dept_id <>", value, "reviewDeptId");
            return (Criteria) this;
        }

        public Criteria andReviewDeptIdGreaterThan(Long value) {
            addCriterion("review_dept_id >", value, "reviewDeptId");
            return (Criteria) this;
        }

        public Criteria andReviewDeptIdGreaterThanOrEqualTo(Long value) {
            addCriterion("review_dept_id >=", value, "reviewDeptId");
            return (Criteria) this;
        }

        public Criteria andReviewDeptIdLessThan(Long value) {
            addCriterion("review_dept_id <", value, "reviewDeptId");
            return (Criteria) this;
        }

        public Criteria andReviewDeptIdLessThanOrEqualTo(Long value) {
            addCriterion("review_dept_id <=", value, "reviewDeptId");
            return (Criteria) this;
        }

        public Criteria andReviewDeptIdIn(List<Long> values) {
            addCriterion("review_dept_id in", values, "reviewDeptId");
            return (Criteria) this;
        }

        public Criteria andReviewDeptIdNotIn(List<Long> values) {
            addCriterion("review_dept_id not in", values, "reviewDeptId");
            return (Criteria) this;
        }

        public Criteria andReviewDeptIdBetween(Long value1, Long value2) {
            addCriterion("review_dept_id between", value1, value2, "reviewDeptId");
            return (Criteria) this;
        }

        public Criteria andReviewDeptIdNotBetween(Long value1, Long value2) {
            addCriterion("review_dept_id not between", value1, value2, "reviewDeptId");
            return (Criteria) this;
        }

        public Criteria andReviewDeptNameIsNull() {
            addCriterion("review_dept_name is null");
            return (Criteria) this;
        }

        public Criteria andReviewDeptNameIsNotNull() {
            addCriterion("review_dept_name is not null");
            return (Criteria) this;
        }

        public Criteria andReviewDeptNameEqualTo(String value) {
            addCriterion("review_dept_name =", value, "reviewDeptName");
            return (Criteria) this;
        }

        public Criteria andReviewDeptNameNotEqualTo(String value) {
            addCriterion("review_dept_name <>", value, "reviewDeptName");
            return (Criteria) this;
        }

        public Criteria andReviewDeptNameGreaterThan(String value) {
            addCriterion("review_dept_name >", value, "reviewDeptName");
            return (Criteria) this;
        }

        public Criteria andReviewDeptNameGreaterThanOrEqualTo(String value) {
            addCriterion("review_dept_name >=", value, "reviewDeptName");
            return (Criteria) this;
        }

        public Criteria andReviewDeptNameLessThan(String value) {
            addCriterion("review_dept_name <", value, "reviewDeptName");
            return (Criteria) this;
        }

        public Criteria andReviewDeptNameLessThanOrEqualTo(String value) {
            addCriterion("review_dept_name <=", value, "reviewDeptName");
            return (Criteria) this;
        }

        public Criteria andReviewDeptNameLike(String value) {
            addCriterion("review_dept_name like", value, "reviewDeptName");
            return (Criteria) this;
        }

        public Criteria andReviewDeptNameNotLike(String value) {
            addCriterion("review_dept_name not like", value, "reviewDeptName");
            return (Criteria) this;
        }

        public Criteria andReviewDeptNameIn(List<String> values) {
            addCriterion("review_dept_name in", values, "reviewDeptName");
            return (Criteria) this;
        }

        public Criteria andReviewDeptNameNotIn(List<String> values) {
            addCriterion("review_dept_name not in", values, "reviewDeptName");
            return (Criteria) this;
        }

        public Criteria andReviewDeptNameBetween(String value1, String value2) {
            addCriterion("review_dept_name between", value1, value2, "reviewDeptName");
            return (Criteria) this;
        }

        public Criteria andReviewDeptNameNotBetween(String value1, String value2) {
            addCriterion("review_dept_name not between", value1, value2, "reviewDeptName");
            return (Criteria) this;
        }

        public Criteria andFinishDateIsNull() {
            addCriterion("finish_date is null");
            return (Criteria) this;
        }

        public Criteria andFinishDateIsNotNull() {
            addCriterion("finish_date is not null");
            return (Criteria) this;
        }

        public Criteria andFinishDateEqualTo(Date value) {
            addCriterion("finish_date =", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateNotEqualTo(Date value) {
            addCriterion("finish_date <>", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateGreaterThan(Date value) {
            addCriterion("finish_date >", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateGreaterThanOrEqualTo(Date value) {
            addCriterion("finish_date >=", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateLessThan(Date value) {
            addCriterion("finish_date <", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateLessThanOrEqualTo(Date value) {
            addCriterion("finish_date <=", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateIn(List<Date> values) {
            addCriterion("finish_date in", values, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateNotIn(List<Date> values) {
            addCriterion("finish_date not in", values, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateBetween(Date value1, Date value2) {
            addCriterion("finish_date between", value1, value2, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateNotBetween(Date value1, Date value2) {
            addCriterion("finish_date not between", value1, value2, "finishDate");
            return (Criteria) this;
        }

        public Criteria andReviewReqIsNull() {
            addCriterion("review_req is null");
            return (Criteria) this;
        }

        public Criteria andReviewReqIsNotNull() {
            addCriterion("review_req is not null");
            return (Criteria) this;
        }

        public Criteria andReviewReqEqualTo(String value) {
            addCriterion("review_req =", value, "reviewReq");
            return (Criteria) this;
        }

        public Criteria andReviewReqNotEqualTo(String value) {
            addCriterion("review_req <>", value, "reviewReq");
            return (Criteria) this;
        }

        public Criteria andReviewReqGreaterThan(String value) {
            addCriterion("review_req >", value, "reviewReq");
            return (Criteria) this;
        }

        public Criteria andReviewReqGreaterThanOrEqualTo(String value) {
            addCriterion("review_req >=", value, "reviewReq");
            return (Criteria) this;
        }

        public Criteria andReviewReqLessThan(String value) {
            addCriterion("review_req <", value, "reviewReq");
            return (Criteria) this;
        }

        public Criteria andReviewReqLessThanOrEqualTo(String value) {
            addCriterion("review_req <=", value, "reviewReq");
            return (Criteria) this;
        }

        public Criteria andReviewReqLike(String value) {
            addCriterion("review_req like", value, "reviewReq");
            return (Criteria) this;
        }

        public Criteria andReviewReqNotLike(String value) {
            addCriterion("review_req not like", value, "reviewReq");
            return (Criteria) this;
        }

        public Criteria andReviewReqIn(List<String> values) {
            addCriterion("review_req in", values, "reviewReq");
            return (Criteria) this;
        }

        public Criteria andReviewReqNotIn(List<String> values) {
            addCriterion("review_req not in", values, "reviewReq");
            return (Criteria) this;
        }

        public Criteria andReviewReqBetween(String value1, String value2) {
            addCriterion("review_req between", value1, value2, "reviewReq");
            return (Criteria) this;
        }

        public Criteria andReviewReqNotBetween(String value1, String value2) {
            addCriterion("review_req not between", value1, value2, "reviewReq");
            return (Criteria) this;
        }

        public Criteria andPlanStageIsNull() {
            addCriterion("plan_stage is null");
            return (Criteria) this;
        }

        public Criteria andPlanStageIsNotNull() {
            addCriterion("plan_stage is not null");
            return (Criteria) this;
        }

        public Criteria andPlanStageEqualTo(String value) {
            addCriterion("plan_stage =", value, "planStage");
            return (Criteria) this;
        }

        public Criteria andPlanStageNotEqualTo(String value) {
            addCriterion("plan_stage <>", value, "planStage");
            return (Criteria) this;
        }

        public Criteria andPlanStageGreaterThan(String value) {
            addCriterion("plan_stage >", value, "planStage");
            return (Criteria) this;
        }

        public Criteria andPlanStageGreaterThanOrEqualTo(String value) {
            addCriterion("plan_stage >=", value, "planStage");
            return (Criteria) this;
        }

        public Criteria andPlanStageLessThan(String value) {
            addCriterion("plan_stage <", value, "planStage");
            return (Criteria) this;
        }

        public Criteria andPlanStageLessThanOrEqualTo(String value) {
            addCriterion("plan_stage <=", value, "planStage");
            return (Criteria) this;
        }

        public Criteria andPlanStageLike(String value) {
            addCriterion("plan_stage like", value, "planStage");
            return (Criteria) this;
        }

        public Criteria andPlanStageNotLike(String value) {
            addCriterion("plan_stage not like", value, "planStage");
            return (Criteria) this;
        }

        public Criteria andPlanStageIn(List<String> values) {
            addCriterion("plan_stage in", values, "planStage");
            return (Criteria) this;
        }

        public Criteria andPlanStageNotIn(List<String> values) {
            addCriterion("plan_stage not in", values, "planStage");
            return (Criteria) this;
        }

        public Criteria andPlanStageBetween(String value1, String value2) {
            addCriterion("plan_stage between", value1, value2, "planStage");
            return (Criteria) this;
        }

        public Criteria andPlanStageNotBetween(String value1, String value2) {
            addCriterion("plan_stage not between", value1, value2, "planStage");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorIsNull() {
            addCriterion("plan_establish_director is null");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorIsNotNull() {
            addCriterion("plan_establish_director is not null");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorEqualTo(String value) {
            addCriterion("plan_establish_director =", value, "planEstablishDirector");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorNotEqualTo(String value) {
            addCriterion("plan_establish_director <>", value, "planEstablishDirector");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorGreaterThan(String value) {
            addCriterion("plan_establish_director >", value, "planEstablishDirector");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorGreaterThanOrEqualTo(String value) {
            addCriterion("plan_establish_director >=", value, "planEstablishDirector");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorLessThan(String value) {
            addCriterion("plan_establish_director <", value, "planEstablishDirector");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorLessThanOrEqualTo(String value) {
            addCriterion("plan_establish_director <=", value, "planEstablishDirector");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorLike(String value) {
            addCriterion("plan_establish_director like", value, "planEstablishDirector");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorNotLike(String value) {
            addCriterion("plan_establish_director not like", value, "planEstablishDirector");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorIn(List<String> values) {
            addCriterion("plan_establish_director in", values, "planEstablishDirector");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorNotIn(List<String> values) {
            addCriterion("plan_establish_director not in", values, "planEstablishDirector");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorBetween(String value1, String value2) {
            addCriterion("plan_establish_director between", value1, value2, "planEstablishDirector");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorNotBetween(String value1, String value2) {
            addCriterion("plan_establish_director not between", value1, value2, "planEstablishDirector");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorIdIsNull() {
            addCriterion("plan_establish_director_id is null");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorIdIsNotNull() {
            addCriterion("plan_establish_director_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorIdEqualTo(Long value) {
            addCriterion("plan_establish_director_id =", value, "planEstablishDirectorId");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorIdNotEqualTo(Long value) {
            addCriterion("plan_establish_director_id <>", value, "planEstablishDirectorId");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorIdGreaterThan(Long value) {
            addCriterion("plan_establish_director_id >", value, "planEstablishDirectorId");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("plan_establish_director_id >=", value, "planEstablishDirectorId");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorIdLessThan(Long value) {
            addCriterion("plan_establish_director_id <", value, "planEstablishDirectorId");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorIdLessThanOrEqualTo(Long value) {
            addCriterion("plan_establish_director_id <=", value, "planEstablishDirectorId");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorIdIn(List<Long> values) {
            addCriterion("plan_establish_director_id in", values, "planEstablishDirectorId");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorIdNotIn(List<Long> values) {
            addCriterion("plan_establish_director_id not in", values, "planEstablishDirectorId");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorIdBetween(Long value1, Long value2) {
            addCriterion("plan_establish_director_id between", value1, value2, "planEstablishDirectorId");
            return (Criteria) this;
        }

        public Criteria andPlanEstablishDirectorIdNotBetween(Long value1, Long value2) {
            addCriterion("plan_establish_director_id not between", value1, value2, "planEstablishDirectorId");
            return (Criteria) this;
        }

        public Criteria andPlanContentIsNull() {
            addCriterion("plan_content is null");
            return (Criteria) this;
        }

        public Criteria andPlanContentIsNotNull() {
            addCriterion("plan_content is not null");
            return (Criteria) this;
        }

        public Criteria andPlanContentEqualTo(String value) {
            addCriterion("plan_content =", value, "planContent");
            return (Criteria) this;
        }

        public Criteria andPlanContentNotEqualTo(String value) {
            addCriterion("plan_content <>", value, "planContent");
            return (Criteria) this;
        }

        public Criteria andPlanContentGreaterThan(String value) {
            addCriterion("plan_content >", value, "planContent");
            return (Criteria) this;
        }

        public Criteria andPlanContentGreaterThanOrEqualTo(String value) {
            addCriterion("plan_content >=", value, "planContent");
            return (Criteria) this;
        }

        public Criteria andPlanContentLessThan(String value) {
            addCriterion("plan_content <", value, "planContent");
            return (Criteria) this;
        }

        public Criteria andPlanContentLessThanOrEqualTo(String value) {
            addCriterion("plan_content <=", value, "planContent");
            return (Criteria) this;
        }

        public Criteria andPlanContentLike(String value) {
            addCriterion("plan_content like", value, "planContent");
            return (Criteria) this;
        }

        public Criteria andPlanContentNotLike(String value) {
            addCriterion("plan_content not like", value, "planContent");
            return (Criteria) this;
        }

        public Criteria andPlanContentIn(List<String> values) {
            addCriterion("plan_content in", values, "planContent");
            return (Criteria) this;
        }

        public Criteria andPlanContentNotIn(List<String> values) {
            addCriterion("plan_content not in", values, "planContent");
            return (Criteria) this;
        }

        public Criteria andPlanContentBetween(String value1, String value2) {
            addCriterion("plan_content between", value1, value2, "planContent");
            return (Criteria) this;
        }

        public Criteria andPlanContentNotBetween(String value1, String value2) {
            addCriterion("plan_content not between", value1, value2, "planContent");
            return (Criteria) this;
        }

        public Criteria andReqSubmitDateIsNull() {
            addCriterion("req_submit_date is null");
            return (Criteria) this;
        }

        public Criteria andReqSubmitDateIsNotNull() {
            addCriterion("req_submit_date is not null");
            return (Criteria) this;
        }

        public Criteria andReqSubmitDateEqualTo(Date value) {
            addCriterion("req_submit_date =", value, "reqSubmitDate");
            return (Criteria) this;
        }

        public Criteria andReqSubmitDateNotEqualTo(Date value) {
            addCriterion("req_submit_date <>", value, "reqSubmitDate");
            return (Criteria) this;
        }

        public Criteria andReqSubmitDateGreaterThan(Date value) {
            addCriterion("req_submit_date >", value, "reqSubmitDate");
            return (Criteria) this;
        }

        public Criteria andReqSubmitDateGreaterThanOrEqualTo(Date value) {
            addCriterion("req_submit_date >=", value, "reqSubmitDate");
            return (Criteria) this;
        }

        public Criteria andReqSubmitDateLessThan(Date value) {
            addCriterion("req_submit_date <", value, "reqSubmitDate");
            return (Criteria) this;
        }

        public Criteria andReqSubmitDateLessThanOrEqualTo(Date value) {
            addCriterion("req_submit_date <=", value, "reqSubmitDate");
            return (Criteria) this;
        }

        public Criteria andReqSubmitDateIn(List<Date> values) {
            addCriterion("req_submit_date in", values, "reqSubmitDate");
            return (Criteria) this;
        }

        public Criteria andReqSubmitDateNotIn(List<Date> values) {
            addCriterion("req_submit_date not in", values, "reqSubmitDate");
            return (Criteria) this;
        }

        public Criteria andReqSubmitDateBetween(Date value1, Date value2) {
            addCriterion("req_submit_date between", value1, value2, "reqSubmitDate");
            return (Criteria) this;
        }

        public Criteria andReqSubmitDateNotBetween(Date value1, Date value2) {
            addCriterion("req_submit_date not between", value1, value2, "reqSubmitDate");
            return (Criteria) this;
        }

        public Criteria andPlanNumIsNull() {
            addCriterion("plan_num is null");
            return (Criteria) this;
        }

        public Criteria andPlanNumIsNotNull() {
            addCriterion("plan_num is not null");
            return (Criteria) this;
        }

        public Criteria andPlanNumEqualTo(Integer value) {
            addCriterion("plan_num =", value, "planNum");
            return (Criteria) this;
        }

        public Criteria andPlanNumNotEqualTo(Integer value) {
            addCriterion("plan_num <>", value, "planNum");
            return (Criteria) this;
        }

        public Criteria andPlanNumGreaterThan(Integer value) {
            addCriterion("plan_num >", value, "planNum");
            return (Criteria) this;
        }

        public Criteria andPlanNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("plan_num >=", value, "planNum");
            return (Criteria) this;
        }

        public Criteria andPlanNumLessThan(Integer value) {
            addCriterion("plan_num <", value, "planNum");
            return (Criteria) this;
        }

        public Criteria andPlanNumLessThanOrEqualTo(Integer value) {
            addCriterion("plan_num <=", value, "planNum");
            return (Criteria) this;
        }

        public Criteria andPlanNumIn(List<Integer> values) {
            addCriterion("plan_num in", values, "planNum");
            return (Criteria) this;
        }

        public Criteria andPlanNumNotIn(List<Integer> values) {
            addCriterion("plan_num not in", values, "planNum");
            return (Criteria) this;
        }

        public Criteria andPlanNumBetween(Integer value1, Integer value2) {
            addCriterion("plan_num between", value1, value2, "planNum");
            return (Criteria) this;
        }

        public Criteria andPlanNumNotBetween(Integer value1, Integer value2) {
            addCriterion("plan_num not between", value1, value2, "planNum");
            return (Criteria) this;
        }

        public Criteria andFinishNumIsNull() {
            addCriterion("finish_num is null");
            return (Criteria) this;
        }

        public Criteria andFinishNumIsNotNull() {
            addCriterion("finish_num is not null");
            return (Criteria) this;
        }

        public Criteria andFinishNumEqualTo(Integer value) {
            addCriterion("finish_num =", value, "finishNum");
            return (Criteria) this;
        }

        public Criteria andFinishNumNotEqualTo(Integer value) {
            addCriterion("finish_num <>", value, "finishNum");
            return (Criteria) this;
        }

        public Criteria andFinishNumGreaterThan(Integer value) {
            addCriterion("finish_num >", value, "finishNum");
            return (Criteria) this;
        }

        public Criteria andFinishNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("finish_num >=", value, "finishNum");
            return (Criteria) this;
        }

        public Criteria andFinishNumLessThan(Integer value) {
            addCriterion("finish_num <", value, "finishNum");
            return (Criteria) this;
        }

        public Criteria andFinishNumLessThanOrEqualTo(Integer value) {
            addCriterion("finish_num <=", value, "finishNum");
            return (Criteria) this;
        }

        public Criteria andFinishNumIn(List<Integer> values) {
            addCriterion("finish_num in", values, "finishNum");
            return (Criteria) this;
        }

        public Criteria andFinishNumNotIn(List<Integer> values) {
            addCriterion("finish_num not in", values, "finishNum");
            return (Criteria) this;
        }

        public Criteria andFinishNumBetween(Integer value1, Integer value2) {
            addCriterion("finish_num between", value1, value2, "finishNum");
            return (Criteria) this;
        }

        public Criteria andFinishNumNotBetween(Integer value1, Integer value2) {
            addCriterion("finish_num not between", value1, value2, "finishNum");
            return (Criteria) this;
        }

        public Criteria andExigencyStatusIsNull() {
            addCriterion("exigency_status is null");
            return (Criteria) this;
        }

        public Criteria andExigencyStatusIsNotNull() {
            addCriterion("exigency_status is not null");
            return (Criteria) this;
        }

        public Criteria andExigencyStatusEqualTo(String value) {
            addCriterion("exigency_status =", value, "exigencyStatus");
            return (Criteria) this;
        }

        public Criteria andExigencyStatusNotEqualTo(String value) {
            addCriterion("exigency_status <>", value, "exigencyStatus");
            return (Criteria) this;
        }

        public Criteria andExigencyStatusGreaterThan(String value) {
            addCriterion("exigency_status >", value, "exigencyStatus");
            return (Criteria) this;
        }

        public Criteria andExigencyStatusGreaterThanOrEqualTo(String value) {
            addCriterion("exigency_status >=", value, "exigencyStatus");
            return (Criteria) this;
        }

        public Criteria andExigencyStatusLessThan(String value) {
            addCriterion("exigency_status <", value, "exigencyStatus");
            return (Criteria) this;
        }

        public Criteria andExigencyStatusLessThanOrEqualTo(String value) {
            addCriterion("exigency_status <=", value, "exigencyStatus");
            return (Criteria) this;
        }

        public Criteria andExigencyStatusLike(String value) {
            addCriterion("exigency_status like", value, "exigencyStatus");
            return (Criteria) this;
        }

        public Criteria andExigencyStatusNotLike(String value) {
            addCriterion("exigency_status not like", value, "exigencyStatus");
            return (Criteria) this;
        }

        public Criteria andExigencyStatusIn(List<String> values) {
            addCriterion("exigency_status in", values, "exigencyStatus");
            return (Criteria) this;
        }

        public Criteria andExigencyStatusNotIn(List<String> values) {
            addCriterion("exigency_status not in", values, "exigencyStatus");
            return (Criteria) this;
        }

        public Criteria andExigencyStatusBetween(String value1, String value2) {
            addCriterion("exigency_status between", value1, value2, "exigencyStatus");
            return (Criteria) this;
        }

        public Criteria andExigencyStatusNotBetween(String value1, String value2) {
            addCriterion("exigency_status not between", value1, value2, "exigencyStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusIsNull() {
            addCriterion("task_status is null");
            return (Criteria) this;
        }

        public Criteria andTaskStatusIsNotNull() {
            addCriterion("task_status is not null");
            return (Criteria) this;
        }

        public Criteria andTaskStatusEqualTo(String value) {
            addCriterion("task_status =", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusNotEqualTo(String value) {
            addCriterion("task_status <>", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusGreaterThan(String value) {
            addCriterion("task_status >", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusGreaterThanOrEqualTo(String value) {
            addCriterion("task_status >=", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusLessThan(String value) {
            addCriterion("task_status <", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusLessThanOrEqualTo(String value) {
            addCriterion("task_status <=", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusLike(String value) {
            addCriterion("task_status like", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusNotLike(String value) {
            addCriterion("task_status not like", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusIn(List<String> values) {
            addCriterion("task_status in", values, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusNotIn(List<String> values) {
            addCriterion("task_status not in", values, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusBetween(String value1, String value2) {
            addCriterion("task_status between", value1, value2, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusNotBetween(String value1, String value2) {
            addCriterion("task_status not between", value1, value2, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andInitUserIdIsNull() {
            addCriterion("init_user_id is null");
            return (Criteria) this;
        }

        public Criteria andInitUserIdIsNotNull() {
            addCriterion("init_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andInitUserIdEqualTo(Long value) {
            addCriterion("init_user_id =", value, "initUserId");
            return (Criteria) this;
        }

        public Criteria andInitUserIdNotEqualTo(Long value) {
            addCriterion("init_user_id <>", value, "initUserId");
            return (Criteria) this;
        }

        public Criteria andInitUserIdGreaterThan(Long value) {
            addCriterion("init_user_id >", value, "initUserId");
            return (Criteria) this;
        }

        public Criteria andInitUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("init_user_id >=", value, "initUserId");
            return (Criteria) this;
        }

        public Criteria andInitUserIdLessThan(Long value) {
            addCriterion("init_user_id <", value, "initUserId");
            return (Criteria) this;
        }

        public Criteria andInitUserIdLessThanOrEqualTo(Long value) {
            addCriterion("init_user_id <=", value, "initUserId");
            return (Criteria) this;
        }

        public Criteria andInitUserIdIn(List<Long> values) {
            addCriterion("init_user_id in", values, "initUserId");
            return (Criteria) this;
        }

        public Criteria andInitUserIdNotIn(List<Long> values) {
            addCriterion("init_user_id not in", values, "initUserId");
            return (Criteria) this;
        }

        public Criteria andInitUserIdBetween(Long value1, Long value2) {
            addCriterion("init_user_id between", value1, value2, "initUserId");
            return (Criteria) this;
        }

        public Criteria andInitUserIdNotBetween(Long value1, Long value2) {
            addCriterion("init_user_id not between", value1, value2, "initUserId");
            return (Criteria) this;
        }

        public Criteria andInitUserNameIsNull() {
            addCriterion("init_user_name is null");
            return (Criteria) this;
        }

        public Criteria andInitUserNameIsNotNull() {
            addCriterion("init_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andInitUserNameEqualTo(String value) {
            addCriterion("init_user_name =", value, "initUserName");
            return (Criteria) this;
        }

        public Criteria andInitUserNameNotEqualTo(String value) {
            addCriterion("init_user_name <>", value, "initUserName");
            return (Criteria) this;
        }

        public Criteria andInitUserNameGreaterThan(String value) {
            addCriterion("init_user_name >", value, "initUserName");
            return (Criteria) this;
        }

        public Criteria andInitUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("init_user_name >=", value, "initUserName");
            return (Criteria) this;
        }

        public Criteria andInitUserNameLessThan(String value) {
            addCriterion("init_user_name <", value, "initUserName");
            return (Criteria) this;
        }

        public Criteria andInitUserNameLessThanOrEqualTo(String value) {
            addCriterion("init_user_name <=", value, "initUserName");
            return (Criteria) this;
        }

        public Criteria andInitUserNameLike(String value) {
            addCriterion("init_user_name like", value, "initUserName");
            return (Criteria) this;
        }

        public Criteria andInitUserNameNotLike(String value) {
            addCriterion("init_user_name not like", value, "initUserName");
            return (Criteria) this;
        }

        public Criteria andInitUserNameIn(List<String> values) {
            addCriterion("init_user_name in", values, "initUserName");
            return (Criteria) this;
        }

        public Criteria andInitUserNameNotIn(List<String> values) {
            addCriterion("init_user_name not in", values, "initUserName");
            return (Criteria) this;
        }

        public Criteria andInitUserNameBetween(String value1, String value2) {
            addCriterion("init_user_name between", value1, value2, "initUserName");
            return (Criteria) this;
        }

        public Criteria andInitUserNameNotBetween(String value1, String value2) {
            addCriterion("init_user_name not between", value1, value2, "initUserName");
            return (Criteria) this;
        }

        public Criteria andInitDateIsNull() {
            addCriterion("init_date is null");
            return (Criteria) this;
        }

        public Criteria andInitDateIsNotNull() {
            addCriterion("init_date is not null");
            return (Criteria) this;
        }

        public Criteria andInitDateEqualTo(Date value) {
            addCriterionForJDBCDate("init_date =", value, "initDate");
            return (Criteria) this;
        }

        public Criteria andInitDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("init_date <>", value, "initDate");
            return (Criteria) this;
        }

        public Criteria andInitDateGreaterThan(Date value) {
            addCriterionForJDBCDate("init_date >", value, "initDate");
            return (Criteria) this;
        }

        public Criteria andInitDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("init_date >=", value, "initDate");
            return (Criteria) this;
        }

        public Criteria andInitDateLessThan(Date value) {
            addCriterionForJDBCDate("init_date <", value, "initDate");
            return (Criteria) this;
        }

        public Criteria andInitDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("init_date <=", value, "initDate");
            return (Criteria) this;
        }

        public Criteria andInitDateIn(List<Date> values) {
            addCriterionForJDBCDate("init_date in", values, "initDate");
            return (Criteria) this;
        }

        public Criteria andInitDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("init_date not in", values, "initDate");
            return (Criteria) this;
        }

        public Criteria andInitDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("init_date between", value1, value2, "initDate");
            return (Criteria) this;
        }

        public Criteria andInitDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("init_date not between", value1, value2, "initDate");
            return (Criteria) this;
        }

        public Criteria andFileGroupIdIsNull() {
            addCriterion("file_group_id is null");
            return (Criteria) this;
        }

        public Criteria andFileGroupIdIsNotNull() {
            addCriterion("file_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andFileGroupIdEqualTo(String value) {
            addCriterion("file_group_id =", value, "fileGroupId");
            return (Criteria) this;
        }

        public Criteria andFileGroupIdNotEqualTo(String value) {
            addCriterion("file_group_id <>", value, "fileGroupId");
            return (Criteria) this;
        }

        public Criteria andFileGroupIdGreaterThan(String value) {
            addCriterion("file_group_id >", value, "fileGroupId");
            return (Criteria) this;
        }

        public Criteria andFileGroupIdGreaterThanOrEqualTo(String value) {
            addCriterion("file_group_id >=", value, "fileGroupId");
            return (Criteria) this;
        }

        public Criteria andFileGroupIdLessThan(String value) {
            addCriterion("file_group_id <", value, "fileGroupId");
            return (Criteria) this;
        }

        public Criteria andFileGroupIdLessThanOrEqualTo(String value) {
            addCriterion("file_group_id <=", value, "fileGroupId");
            return (Criteria) this;
        }

        public Criteria andFileGroupIdLike(String value) {
            addCriterion("file_group_id like", value, "fileGroupId");
            return (Criteria) this;
        }

        public Criteria andFileGroupIdNotLike(String value) {
            addCriterion("file_group_id not like", value, "fileGroupId");
            return (Criteria) this;
        }

        public Criteria andFileGroupIdIn(List<String> values) {
            addCriterion("file_group_id in", values, "fileGroupId");
            return (Criteria) this;
        }

        public Criteria andFileGroupIdNotIn(List<String> values) {
            addCriterion("file_group_id not in", values, "fileGroupId");
            return (Criteria) this;
        }

        public Criteria andFileGroupIdBetween(String value1, String value2) {
            addCriterion("file_group_id between", value1, value2, "fileGroupId");
            return (Criteria) this;
        }

        public Criteria andFileGroupIdNotBetween(String value1, String value2) {
            addCriterion("file_group_id not between", value1, value2, "fileGroupId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIsNull() {
            addCriterion("create_user_name is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIsNotNull() {
            addCriterion("create_user_name is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameEqualTo(String value) {
            addCriterion("create_user_name =", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotEqualTo(String value) {
            addCriterion("create_user_name <>", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameGreaterThan(String value) {
            addCriterion("create_user_name >", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("create_user_name >=", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLessThan(String value) {
            addCriterion("create_user_name <", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLessThanOrEqualTo(String value) {
            addCriterion("create_user_name <=", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLike(String value) {
            addCriterion("create_user_name like", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotLike(String value) {
            addCriterion("create_user_name not like", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIn(List<String> values) {
            addCriterion("create_user_name in", values, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotIn(List<String> values) {
            addCriterion("create_user_name not in", values, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameBetween(String value1, String value2) {
            addCriterion("create_user_name between", value1, value2, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotBetween(String value1, String value2) {
            addCriterion("create_user_name not between", value1, value2, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDelUserIsNull() {
            addCriterion("del_user is null");
            return (Criteria) this;
        }

        public Criteria andDelUserIsNotNull() {
            addCriterion("del_user is not null");
            return (Criteria) this;
        }

        public Criteria andDelUserEqualTo(String value) {
            addCriterion("del_user =", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserNotEqualTo(String value) {
            addCriterion("del_user <>", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserGreaterThan(String value) {
            addCriterion("del_user >", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserGreaterThanOrEqualTo(String value) {
            addCriterion("del_user >=", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserLessThan(String value) {
            addCriterion("del_user <", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserLessThanOrEqualTo(String value) {
            addCriterion("del_user <=", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserLike(String value) {
            addCriterion("del_user like", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserNotLike(String value) {
            addCriterion("del_user not like", value, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserIn(List<String> values) {
            addCriterion("del_user in", values, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserNotIn(List<String> values) {
            addCriterion("del_user not in", values, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserBetween(String value1, String value2) {
            addCriterion("del_user between", value1, value2, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelUserNotBetween(String value1, String value2) {
            addCriterion("del_user not between", value1, value2, "delUser");
            return (Criteria) this;
        }

        public Criteria andDelTimeIsNull() {
            addCriterion("del_time is null");
            return (Criteria) this;
        }

        public Criteria andDelTimeIsNotNull() {
            addCriterion("del_time is not null");
            return (Criteria) this;
        }

        public Criteria andDelTimeEqualTo(Date value) {
            addCriterion("del_time =", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeNotEqualTo(Date value) {
            addCriterion("del_time <>", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeGreaterThan(Date value) {
            addCriterion("del_time >", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("del_time >=", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeLessThan(Date value) {
            addCriterion("del_time <", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeLessThanOrEqualTo(Date value) {
            addCriterion("del_time <=", value, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeIn(List<Date> values) {
            addCriterion("del_time in", values, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeNotIn(List<Date> values) {
            addCriterion("del_time not in", values, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeBetween(Date value1, Date value2) {
            addCriterion("del_time between", value1, value2, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelTimeNotBetween(Date value1, Date value2) {
            addCriterion("del_time not between", value1, value2, "delTime");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNull() {
            addCriterion("del_flag is null");
            return (Criteria) this;
        }

        public Criteria andDelFlagIsNotNull() {
            addCriterion("del_flag is not null");
            return (Criteria) this;
        }

        public Criteria andDelFlagEqualTo(String value) {
            addCriterion("del_flag =", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotEqualTo(String value) {
            addCriterion("del_flag <>", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThan(String value) {
            addCriterion("del_flag >", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagGreaterThanOrEqualTo(String value) {
            addCriterion("del_flag >=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThan(String value) {
            addCriterion("del_flag <", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLessThanOrEqualTo(String value) {
            addCriterion("del_flag <=", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagLike(String value) {
            addCriterion("del_flag like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotLike(String value) {
            addCriterion("del_flag not like", value, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagIn(List<String> values) {
            addCriterion("del_flag in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotIn(List<String> values) {
            addCriterion("del_flag not in", values, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagBetween(String value1, String value2) {
            addCriterion("del_flag between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andDelFlagNotBetween(String value1, String value2) {
            addCriterion("del_flag not between", value1, value2, "delFlag");
            return (Criteria) this;
        }

        public Criteria andPtVar1IsNull() {
            addCriterion("pt_var1 is null");
            return (Criteria) this;
        }

        public Criteria andPtVar1IsNotNull() {
            addCriterion("pt_var1 is not null");
            return (Criteria) this;
        }

        public Criteria andPtVar1EqualTo(String value) {
            addCriterion("pt_var1 =", value, "ptVar1");
            return (Criteria) this;
        }

        public Criteria andPtVar1NotEqualTo(String value) {
            addCriterion("pt_var1 <>", value, "ptVar1");
            return (Criteria) this;
        }

        public Criteria andPtVar1GreaterThan(String value) {
            addCriterion("pt_var1 >", value, "ptVar1");
            return (Criteria) this;
        }

        public Criteria andPtVar1GreaterThanOrEqualTo(String value) {
            addCriterion("pt_var1 >=", value, "ptVar1");
            return (Criteria) this;
        }

        public Criteria andPtVar1LessThan(String value) {
            addCriterion("pt_var1 <", value, "ptVar1");
            return (Criteria) this;
        }

        public Criteria andPtVar1LessThanOrEqualTo(String value) {
            addCriterion("pt_var1 <=", value, "ptVar1");
            return (Criteria) this;
        }

        public Criteria andPtVar1Like(String value) {
            addCriterion("pt_var1 like", value, "ptVar1");
            return (Criteria) this;
        }

        public Criteria andPtVar1NotLike(String value) {
            addCriterion("pt_var1 not like", value, "ptVar1");
            return (Criteria) this;
        }

        public Criteria andPtVar1In(List<String> values) {
            addCriterion("pt_var1 in", values, "ptVar1");
            return (Criteria) this;
        }

        public Criteria andPtVar1NotIn(List<String> values) {
            addCriterion("pt_var1 not in", values, "ptVar1");
            return (Criteria) this;
        }

        public Criteria andPtVar1Between(String value1, String value2) {
            addCriterion("pt_var1 between", value1, value2, "ptVar1");
            return (Criteria) this;
        }

        public Criteria andPtVar1NotBetween(String value1, String value2) {
            addCriterion("pt_var1 not between", value1, value2, "ptVar1");
            return (Criteria) this;
        }

        public Criteria andPtVar2IsNull() {
            addCriterion("pt_var2 is null");
            return (Criteria) this;
        }

        public Criteria andPtVar2IsNotNull() {
            addCriterion("pt_var2 is not null");
            return (Criteria) this;
        }

        public Criteria andPtVar2EqualTo(String value) {
            addCriterion("pt_var2 =", value, "ptVar2");
            return (Criteria) this;
        }

        public Criteria andPtVar2NotEqualTo(String value) {
            addCriterion("pt_var2 <>", value, "ptVar2");
            return (Criteria) this;
        }

        public Criteria andPtVar2GreaterThan(String value) {
            addCriterion("pt_var2 >", value, "ptVar2");
            return (Criteria) this;
        }

        public Criteria andPtVar2GreaterThanOrEqualTo(String value) {
            addCriterion("pt_var2 >=", value, "ptVar2");
            return (Criteria) this;
        }

        public Criteria andPtVar2LessThan(String value) {
            addCriterion("pt_var2 <", value, "ptVar2");
            return (Criteria) this;
        }

        public Criteria andPtVar2LessThanOrEqualTo(String value) {
            addCriterion("pt_var2 <=", value, "ptVar2");
            return (Criteria) this;
        }

        public Criteria andPtVar2Like(String value) {
            addCriterion("pt_var2 like", value, "ptVar2");
            return (Criteria) this;
        }

        public Criteria andPtVar2NotLike(String value) {
            addCriterion("pt_var2 not like", value, "ptVar2");
            return (Criteria) this;
        }

        public Criteria andPtVar2In(List<String> values) {
            addCriterion("pt_var2 in", values, "ptVar2");
            return (Criteria) this;
        }

        public Criteria andPtVar2NotIn(List<String> values) {
            addCriterion("pt_var2 not in", values, "ptVar2");
            return (Criteria) this;
        }

        public Criteria andPtVar2Between(String value1, String value2) {
            addCriterion("pt_var2 between", value1, value2, "ptVar2");
            return (Criteria) this;
        }

        public Criteria andPtVar2NotBetween(String value1, String value2) {
            addCriterion("pt_var2 not between", value1, value2, "ptVar2");
            return (Criteria) this;
        }

        public Criteria andPtVar3IsNull() {
            addCriterion("pt_var3 is null");
            return (Criteria) this;
        }

        public Criteria andPtVar3IsNotNull() {
            addCriterion("pt_var3 is not null");
            return (Criteria) this;
        }

        public Criteria andPtVar3EqualTo(String value) {
            addCriterion("pt_var3 =", value, "ptVar3");
            return (Criteria) this;
        }

        public Criteria andPtVar3NotEqualTo(String value) {
            addCriterion("pt_var3 <>", value, "ptVar3");
            return (Criteria) this;
        }

        public Criteria andPtVar3GreaterThan(String value) {
            addCriterion("pt_var3 >", value, "ptVar3");
            return (Criteria) this;
        }

        public Criteria andPtVar3GreaterThanOrEqualTo(String value) {
            addCriterion("pt_var3 >=", value, "ptVar3");
            return (Criteria) this;
        }

        public Criteria andPtVar3LessThan(String value) {
            addCriterion("pt_var3 <", value, "ptVar3");
            return (Criteria) this;
        }

        public Criteria andPtVar3LessThanOrEqualTo(String value) {
            addCriterion("pt_var3 <=", value, "ptVar3");
            return (Criteria) this;
        }

        public Criteria andPtVar3Like(String value) {
            addCriterion("pt_var3 like", value, "ptVar3");
            return (Criteria) this;
        }

        public Criteria andPtVar3NotLike(String value) {
            addCriterion("pt_var3 not like", value, "ptVar3");
            return (Criteria) this;
        }

        public Criteria andPtVar3In(List<String> values) {
            addCriterion("pt_var3 in", values, "ptVar3");
            return (Criteria) this;
        }

        public Criteria andPtVar3NotIn(List<String> values) {
            addCriterion("pt_var3 not in", values, "ptVar3");
            return (Criteria) this;
        }

        public Criteria andPtVar3Between(String value1, String value2) {
            addCriterion("pt_var3 between", value1, value2, "ptVar3");
            return (Criteria) this;
        }

        public Criteria andPtVar3NotBetween(String value1, String value2) {
            addCriterion("pt_var3 not between", value1, value2, "ptVar3");
            return (Criteria) this;
        }

        public Criteria andPtVar4IsNull() {
            addCriterion("pt_var4 is null");
            return (Criteria) this;
        }

        public Criteria andPtVar4IsNotNull() {
            addCriterion("pt_var4 is not null");
            return (Criteria) this;
        }

        public Criteria andPtVar4EqualTo(String value) {
            addCriterion("pt_var4 =", value, "ptVar4");
            return (Criteria) this;
        }

        public Criteria andPtVar4NotEqualTo(String value) {
            addCriterion("pt_var4 <>", value, "ptVar4");
            return (Criteria) this;
        }

        public Criteria andPtVar4GreaterThan(String value) {
            addCriterion("pt_var4 >", value, "ptVar4");
            return (Criteria) this;
        }

        public Criteria andPtVar4GreaterThanOrEqualTo(String value) {
            addCriterion("pt_var4 >=", value, "ptVar4");
            return (Criteria) this;
        }

        public Criteria andPtVar4LessThan(String value) {
            addCriterion("pt_var4 <", value, "ptVar4");
            return (Criteria) this;
        }

        public Criteria andPtVar4LessThanOrEqualTo(String value) {
            addCriterion("pt_var4 <=", value, "ptVar4");
            return (Criteria) this;
        }

        public Criteria andPtVar4Like(String value) {
            addCriterion("pt_var4 like", value, "ptVar4");
            return (Criteria) this;
        }

        public Criteria andPtVar4NotLike(String value) {
            addCriterion("pt_var4 not like", value, "ptVar4");
            return (Criteria) this;
        }

        public Criteria andPtVar4In(List<String> values) {
            addCriterion("pt_var4 in", values, "ptVar4");
            return (Criteria) this;
        }

        public Criteria andPtVar4NotIn(List<String> values) {
            addCriterion("pt_var4 not in", values, "ptVar4");
            return (Criteria) this;
        }

        public Criteria andPtVar4Between(String value1, String value2) {
            addCriterion("pt_var4 between", value1, value2, "ptVar4");
            return (Criteria) this;
        }

        public Criteria andPtVar4NotBetween(String value1, String value2) {
            addCriterion("pt_var4 not between", value1, value2, "ptVar4");
            return (Criteria) this;
        }

        public Criteria andPtVar5IsNull() {
            addCriterion("pt_var5 is null");
            return (Criteria) this;
        }

        public Criteria andPtVar5IsNotNull() {
            addCriterion("pt_var5 is not null");
            return (Criteria) this;
        }

        public Criteria andPtVar5EqualTo(String value) {
            addCriterion("pt_var5 =", value, "ptVar5");
            return (Criteria) this;
        }

        public Criteria andPtVar5NotEqualTo(String value) {
            addCriterion("pt_var5 <>", value, "ptVar5");
            return (Criteria) this;
        }

        public Criteria andPtVar5GreaterThan(String value) {
            addCriterion("pt_var5 >", value, "ptVar5");
            return (Criteria) this;
        }

        public Criteria andPtVar5GreaterThanOrEqualTo(String value) {
            addCriterion("pt_var5 >=", value, "ptVar5");
            return (Criteria) this;
        }

        public Criteria andPtVar5LessThan(String value) {
            addCriterion("pt_var5 <", value, "ptVar5");
            return (Criteria) this;
        }

        public Criteria andPtVar5LessThanOrEqualTo(String value) {
            addCriterion("pt_var5 <=", value, "ptVar5");
            return (Criteria) this;
        }

        public Criteria andPtVar5Like(String value) {
            addCriterion("pt_var5 like", value, "ptVar5");
            return (Criteria) this;
        }

        public Criteria andPtVar5NotLike(String value) {
            addCriterion("pt_var5 not like", value, "ptVar5");
            return (Criteria) this;
        }

        public Criteria andPtVar5In(List<String> values) {
            addCriterion("pt_var5 in", values, "ptVar5");
            return (Criteria) this;
        }

        public Criteria andPtVar5NotIn(List<String> values) {
            addCriterion("pt_var5 not in", values, "ptVar5");
            return (Criteria) this;
        }

        public Criteria andPtVar5Between(String value1, String value2) {
            addCriterion("pt_var5 between", value1, value2, "ptVar5");
            return (Criteria) this;
        }

        public Criteria andPtVar5NotBetween(String value1, String value2) {
            addCriterion("pt_var5 not between", value1, value2, "ptVar5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qqch_review
     *
     * @mbggenerated do_not_delete_during_merge Tue Jul 18 16:13:22 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qqch_review
     *
     * @mbggenerated Tue Jul 18 16:13:22 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}